Add training data to experiment test
This MR brings us one step closer to the finalization of #555.

Add generated training images to the experiment repository
Integrate this test data to the automatically run experiment


Former-commit-id: dfcc047a882415b27b1275477c4451bfbd0b99ea [formerly 9eda753b3797d1b9cc2f2cbd547646b7e6bef094]

Former-commit-id: ed557705dc952898d9ac942fb347f8dc9ea948ab

diff --git a/bin/tests/test-verify-mlreef-yml b/bin/tests/test-verify-mlreef-yml
--- a/bin/tests/test-verify-mlreef-yml
+++ b/bin/tests/test-verify-mlreef-yml
@@ -36,7 +36,7 @@ echo "Targeting download branch $EXPERIMENT_BRANCH"
 
 
 curl "http://$URL:10080/api/v4/projects/$GITLAB_PROJECT_ID/repository/files/.mlreef.yml?ref=$EXPERIMENT_BRANCH" \
-  --request GET --fail                          \
+  --request GET                                     \
   | jq > out/test/download-mlreef-yml.response.json
 
 
@@ -53,7 +53,7 @@ TEST="registry.gitlab.com/mlreef/mlreef/epf:$CI_COMMIT_REF_SLUG"
 if grep -q "$TEST" out/test/download-mlreef.yml; then
   echo "SUCCESS: found $TEST in mlreef.yml"
 else
-  echo "FAIL: could not find $TEST in mlreef.yml"
+  echo "FAILURE: could not find $TEST in mlreef.yml"
   FAIL="true"
 fi
 
@@ -62,7 +62,7 @@ TEST="api/v1/epf/experiments/"
 if grep -q "$TEST" out/test/download-mlreef.yml; then
   echo "SUCCESS: found $TEST in mlreef.yml"
 else
-  echo >&2 "FAIL: could not find $TEST in mlreef.yml"
+  echo >&2 "FAILURE: could not find $TEST in mlreef.yml"
   FAIL="true"
 fi
 
