Improve CI framework
* Move the backend compilation to the Dockerfile to increase the reproducibility of builds
  * keeps the `ci-compile-backend` script, because tests cannot (yet) be performed during the docker build
* Modularise the installation script ... because it has become too big for easy maintenance
* let bash script tests fail earlier and "louder"
* deletes incorrect gradle wrapper and settings from repo root


Former-commit-id: a16cf48ffbed1f7d1145d5726000467a42bb47fb [formerly d984ab9a533969bd57531833f6c4a4e890f369f8]

Former-commit-id: d3b85f5140938d41799dd15f376c9765c53d919b

diff --git a/bin/tests/test-create-user-and-project b/bin/tests/test-create-user-and-project
--- a/bin/tests/test-create-user-and-project
+++ b/bin/tests/test-create-user-and-project
@@ -19,7 +19,7 @@ export USER="SMOKE-TEST-$(randomString 3)"
 export PASSWORD="password"
 log "Username is $USER with password "
 export TOKEN #declare separately to be able to gather return value
-curl "http://$URL/api/v1/auth/register" -X POST \
+curl "http://$URL:8080/api/v1/auth/register" -X POST \
   --request POST --fail --show-error            \
   --header 'Content-Type: application/json'   \
   --header 'Accept: application/json'         \
@@ -34,10 +34,16 @@ curl "http://$URL/api/v1/auth/register" -X POST \
 
 jq -r ".token" < out/test/register.response.tmp > out/test/token.tmp
 export TOKEN="$(cat out/test/token.tmp)"
+if [ "$TOKEN" = "" ]; then
+  echo >&2 "ERROR: TOKEN is empty."
+  cat out/test/token.tmp
+  cat out/test/register.response.tmp
+  exit 1
+fi
 
 log "Registering exited with $? and produced token $TOKEN"
 
-curl "http://$URL/api/v1/data-projects" -X POST \
+curl "http://$URL:8080/api/v1/data-projects" -X POST \
   --request POST --fail --show-error            \
   --header "PRIVATE-TOKEN: $TOKEN"            \
   --header "Content-Type: application/json"   \
