Activate end2end test
Former-commit-id: 429247c668e259ceec58302604fc55411bc67fb7 [formerly 8467e51b34731f0b7cf36e851e4f40d9a7897bc5]

Former-commit-id: a261674ca686becf644e179b72d04b95cce63fc3

diff --git a/bin/tests/test-verify-mlreef-yml b/bin/tests/test-verify-mlreef-yml
--- a/bin/tests/test-verify-mlreef-yml
+++ b/bin/tests/test-verify-mlreef-yml
@@ -15,22 +15,23 @@ set -u    # error on usage of undefined variables
 
 
 if [ -z ${TOKEN+x} ]; then
-  echo >&2 "ERROR: The test 'verify-mlreef' needs the environment variable TOKEN."
+  echo >&2 "ERROR 'verify-mlreef': Missing environment variable TOKEN."
   exit 1
 fi
 
 if [ -z ${GITLAB_PROJECT_ID+x} ]; then
-  echo >&2 "ERROR: The test 'verify-mlreef' needs the environment variable GITLAB_PROJECT_ID."
+  echo >&2 "ERROR 'verify-mlreef': Missing environment variable GITLAB_PROJECT_ID."
   exit 1
 fi
 
-if [ -z ${EXPERIMENT_BRANCH+x} ]; then
+if [ -z ${EXPERIMENT_BRANCH+x} ] && [ -f out/test/experiment-branch.tmp ]; then
   export EXPERIMENT_BRANCH=$(cat out/test/experiment-branch.tmp)
 fi
 if [ "$EXPERIMENT_BRANCH" = "" ]; then
-  echo >&2 "ERROR: EXPERIMENT_BRANCH is empty"
+  echo >&2 "ERROR 'verify-mlreef': Missing environment variable EXPERIMENT_BRANCH. Fallback parsing from file 'out/test/experiment-branch.tmp' also failed:"
+  cat out/test/experiment-branch.tmp
   exit 1
-fi;
+fi
 echo "Targeting download branch $EXPERIMENT_BRANCH"
 
 
